name: Deploy RFC
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Get version of the project
        id: project-version
        uses: "euberdeveloper/ga-project-version@main"

      - name: Install mmark
        run: ./scripts/install_mmark.sh

      - name: Install Xml2Rfc
        run: sudo apt-get install -y xml2rfc

      - name: Generate main.md from template
        run: node scripts/generate.js

      - name: Generate xml for RFC
        run: bin/mmark source/main.md > output/spec.xml

      - name: Generate final output
        run: xml2rfc output/spec.xml --v3 --html --pdf --text

      - name: Compresses output
        uses: master-atul/tar-action@v1.0.2
        id: compressed_output
        with:
          command: c
          files: |
            ./output
          outPath: specs.tar.gz

      - name: Add release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.project-version.outputs.version }}"
          prerelease: false
          title: "Deploy of protocol specs"
          files: |
            specs.tar.gz

      - name: Upoad artifact
        uses: actions/upload-artifact@v2
        with:
          name: rfc
          path: output
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: rfc
          path: rfc

      - name: Rename index.html
        run: mv rfc/spec.html rfc/index.html

      - name: Push to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: docs
          clean: true

